### ISSUE TITLE
Last build crashes server, attempts to load font render classes.

### ISSUE THREAD

**Issue by observeroftime02** [Technus/TecTech#18]
Just going to leave the [crash report](https://pastebin.com/BG62qwQh) here.

Looks like TT is trying to load a font render class on the server. This kills the server, obviously. Version works fine in the client. Just the headless server that is affected.

Last build that loads properly is Jenkins 374 from Sept 14th.

**Comment by Technus** [comment]
Yeah i fixed this once but might be bass doing some things where they shouldnt be done

**Comment by Technus** [comment]
https://github.com/Technus/TecTech/commit/6de16576d65b7f02123bb400f063200c41ee7cab

**Comment by Technus** [comment]
https://github.com/Technus/TecTech/commit/e749b1e4aa03300d89c4fc4f7715febc45f03111
