### ISSUE TITLE
Client Side code running on server causes crash

### ISSUE THREAD

**Issue by Matthewacon** [Technus/TecTech#2]
The class `GT_MetaTileEntity_MultiblockBAse_EM` accesses some property of `net/minecraft/client/renderer/texture/IIconRegister` and throws `java.lang.NoClassDefFoundError` as a result. 

Stack Trace: https://pastebin.com/f0y6Nxpe
If you need the log file, I can also upload it to pastebin

**Comment by Technus** [comment]
Should be resolved, reopen if needed. 
https://github.com/Technus/TecTech/commit/2b5bb4a38eb644a41bb1d74bd4e90fa818ace336
(will require lastest GTNH fork of GT5u to run http://jenkins.usrv.de:8081/job/Gregtech-5-Unofficial/)
