### ISSUE TITLE
Inconsistent recipe for the ZPM voltage turbo charger

### ISSUE THREAD

**Issue by Alexdoru** [Technus/TecTech#20]
The ZPM voltage turbo charger requires LuV batteries to craft instead of batteries of the same voltage.

Playing with GTNH 2.0.7.5

**Comment by Technus** [comment]
@Spartak1997

**Comment by Spartak1997** [comment]
I will try fix it today

**Comment by Spartak1997** [comment]
@Alexdoru https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/97

**Comment by Spartak1997** [comment]
@Technus it's done. You can close issue

**Comment by basdxz** [comment]
Issue closed as requested
