### ISSUE TITLE
Add recipe for IV-ZPM high amp energy hatches

### ISSUE THREAD

**Issue by Impos913** [Technus/TecTech#25]
Using GTNH-2.0.8.8

Currently only UV+ high amp energy hatches have a recipe.
Add recipe for IV-ZPM ones.

**Comment by Technus** [comment]
Closed by @Dream-Master

**Comment by Impos913** [comment]
IV 4A, IV 16A and IV 64A Energy Hatches require Rhodium-Plated Palladium Plates to craft while they should require Tungstensteel Plates. LuV 4A, LuV 16A and LuV 64A Energy Hatches require Iridium Plates to craft while they should require Rhodium-Plated Palladium Plates. 
Also, IV 16A and IV 64A Energy Hatches require LuV 4A and LuV 16A Energy Hatches to craft while they should require IV 4A and IV 16A Energy Hatches.

Please fix recipes.

**Comment by Technus** [comment]
@Dream-Master

**Comment by Dream-Master** [comment]
will fix

**Comment by Dream-Master** [comment]
fixed with http://jenkins.usrv.eu:8080/job/Tec%20Tech/431/
