### ISSUE TITLE
missing recipes

### ISSUE THREAD

**Issue by adamcirillo** [Technus/TecTech#3]
I added the mod to my GT pack with 5.09.31pre4 all your machines have no recipes or am I missing something to unlock them?

**Comment by SirFell** [comment]
Mod was created for GT New Horizons, so might be only having recipes in [nh-recipes](https://github.com/Technus/TecTech/tree/nh-recipes) branch. To get ancwer from @Technus you will need to wait.

**Comment by Dream-Master** [comment]
yes, [nh-recipes](https://github.com/Technus/TecTech/tree/nh-recipes) has ~25% of mod recipes covered.

*Edited by @SirAzazel: Fixed DreamDerp*

**Comment by adamcirillo** [comment]
well I found out about the mod as it was in the readme for gt5u GitHub and checked it out so I was thinking off adding it

**Comment by SirFell** [comment]
You technically can do whatever with it since its under MIT License, but to make mod run you will have to use GTNH GT5U, GTNH Core, YAMCore alongside with other normal mod requirements.

**Comment by adamcirillo** [comment]
what's the difference with the GTNH version of gregtech I played the pack up to LV but then quit after getting killed by mobs  all the time

**Comment by SirFell** [comment]
its still modification of BoodAsps GT5U, but its made to better suit modpack. To see actual differences - compare repositories on github.

**Comment by Technus** [comment]
the dependencies for GTNH stuff should be soft ones in master branch. recipes can be easily added for the main branch also but it is low priority now, unless pullrequests appear.

**Comment by Technus** [comment]
The mod is under development of the featues more than the development of simple code.

**Comment by adamcirillo** [comment]
that's fine I understand the pack i'm making isn't going to be ready for a while just wanted to know what was going I could minetweak recipes if I have since i'm no programmer
