### ISSUE TITLE
Uncertainty Resolver has no recipe

### ISSUE THREAD

**Issue by Prometheus0000** [Technus/TecTech#32]
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6217

Unless this problem is GTNH specific, in which case please say so. It used to have a recipe too.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/84375074-4c09f880-abdf-11ea-8dc0-d663ca7a4508.png)
![image](https://user-images.githubusercontent.com/2970688/84375087-50ceac80-abdf-11ea-978e-238c97f3ae72.png)
