### ISSUE TITLE
The Quantum Computer doesn't seem to do a structure check until you turn it on

### ISSUE THREAD

**Issue by Prometheus0000** [Technus/TecTech#34]
Specifically, the blocks (like an energy hatch) don't change color to match until it's turned on.
GTNH 2.0.9.0 RC2

**Comment by Technus** [comment]
Cannot reproduce?

**Comment by Technus** [comment]
When I built it from scratch it worked.

**Comment by Technus** [comment]
@Prometheus0000

**Comment by Prometheus0000** [comment]
Maybe it's when you change them?

**Comment by Prometheus0000** [comment]
I can't get it to happen anymore, sorry. Maybe it's something inconsistent?

I also noticed that Advanced Heat Vents act as some kind of 'Fan Cover' for tile entity blocks, is this something you added? Or have any functionality for reducing heat? I thought I was supposed to put them in the rack?

**Comment by Technus** [comment]
It is some native GT behaviour cover. It was supposed to reduce nergy use or smth.
