### ISSUE TITLE
The tesla tower states it need titanium frames boxes when it does not

### ISSUE THREAD

**Issue by Prometheus0000** [Technus/TecTech#54]
![image](https://user-images.githubusercontent.com/8517039/115794204-9b8e8880-a39b-11eb-9b73-e78d622d6a55.png)
But works fine with any frame.

Please either change the text to something else, or make it actually need titanium.

**Comment by basdxz** [comment]
Intended behaviour.

**Comment by GTNH-Colen** [comment]
> Intended behaviour.

It's intended for the tooltip to be wrong? Knowing TT that would make sense 😂
