### ISSUE TITLE
[Bug] [1.7.10] Crash on version 5.0.6-12 using both Build from Jenkins and GitHub release

### ISSUE THREAD

**Issue by ThePixelist** [Technus/TecTech#63]
Jenkin build details:
TecTech jar: TecTech-1.7.10-5.0.6-12-g6646aa2.jar
[Crash report](https://file.garden/XqA-al1bbgcDmDpx/crash-2022-06-22_13.15.33-client.txt)
[Log](https://file.garden/XqA-al1bbgcDmDpx/2022-06-22-4.log)
Mods: CodeChickenCore, GT5u, IC2, NEI, StructureLib, TecTech, YAMCore

If I need to include more info, please tell me.

**Comment by Technus** [comment]
Wrong GT version.
