### ISSUE TITLE
THIS MOD IS PROBABLY HACKED

### ISSUE THREAD

**Issue by salt-y-lemons** [Technus/TecTech#72]
ATTENTION PEOPLE, This mod has been reported to be infected with a virus and it will hack and spread your personal info.
DO NOT DOWNLOAD IT

For more info go here: https://github.com/dogboy21/serializationisbad
Or here: https://youtu.be/7YcPMmVSTto

**Comment by Dream-Master** [comment]
we make a fix at https://github.com/GTNewHorizons/TecTech
