### ISSUE TITLE
Crashes FTB Infinity Evolved 

### ISSUE THREAD

**Issue by Clowcadia** [Technus/TecTech#8]
I am trying to import some of the main mods from GT New horizons to infinity evolved, to play with expert mode. and this is the one mod that does crashes the client. trying to round down what mod its in compatible with but mean while here is a crash report

**Comment by draknyte1** [comment]
I don't understand why Tec is trying to 'fix' blocks but one of the mods it iterates is probably missing. 

Please put remove your crash log from your OP and put it onto pastie or pastebin. Trying to scroll down 1500 lines on mobile isn't very nice.

**Comment by Clowcadia** [comment]
I am sorry heres the paste bing link
https://pastebin.com/YEYd0tkw

**Comment by draknyte1** [comment]
```
private void fixBlocks(){
        HashSet<String> modIDs=new HashSet<>(Arrays.asList(
                "minecraft",
                "IC2",
                "gregtech",
                "dreamcraft",
                "miscutils",
                "GT++DarkWorld",
                "GalacticraftCore",
                "GalacticraftMars",
                "GalaxySpace",
                "extracells",
                "Avaritia",
                "avaritiaddons",
                "EnderStorage",
                "enhancedportals",
                "DraconicEvolution",
                "IC2NuclearControl",
                "IronChest",
                "opensecurity",
                "openmodularturrets",
                "Railcraft",
                "RIO",
                "SGCraft",
                "appliedenergistics2",
                "thaumicenergistics",
                "witchery",
                "lootgames",
                "utilityworlds",
                Reference.MODID
        ));
```

**Comment by Clowcadia** [comment]
what does that entail, are those required mods for the tec tech mod?

**Comment by Clowcadia** [comment]
the thing is i tried to import ftb infinity evolved mods int gt new horizons and it broke that way too

**Comment by draknyte1** [comment]
I can't really say without being on a computer (currently in Japan and looking via mobile browser). Try launch one of those modified packs without TecTech. That'll be helpful if you could?

**Comment by Clowcadia** [comment]
it works fine with out tec tec, but when i found this and its wiki, i am quiet intrested in using this mod, wish it was compatible. and thank you

**Comment by draknyte1** [comment]
You can play without it for the entire early game and add it later once Tec fixes it, no hassle. :)

**Comment by Clowcadia** [comment]
ok gotcha, hope he knows hes new mod now got some good attention

**Comment by Technus** [comment]
http://jenkins.usrv.de:8081/job/Tec%20Tech/ try with build 114 and then 115, both should work. If that is the same issue that got resolved long time ago. If not 115 should work 🤔 .

**Comment by Technus** [comment]
reopen if need be
